package mahadevfoam_dealers;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement; 
import java.sql.ResultSet;
*/


import java.lang.annotation.Annotation;
import mahadevfoam_dealers.Dealer_Portal;
import mahadevfoam_dealers.dealer_details_portal;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mahadav
 */
public class Add_region_form extends javax.swing.JFrame {

    /**
     * Creates new form Add_region_form
     */
    public Add_region_form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jregiontable = new javax.swing.JTable();
        searchbutton = new javax.swing.JButton();
        viewallbutton = new javax.swing.JButton();
        backbutton = new javax.swing.JButton();
        addregionbutton = new javax.swing.JButton();
        jTfaddregion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Region update");
        setPreferredSize(new java.awt.Dimension(530, 340));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));
        jPanel1.setLayout(null);

        jregiontable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Region list"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jregiontable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(330, 90, 170, 190);

        searchbutton.setBackground(new java.awt.Color(97, 212, 195));
        searchbutton.setText("Search");
        searchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(searchbutton);
        searchbutton.setBounds(210, 250, 90, 30);

        viewallbutton.setBackground(new java.awt.Color(97, 212, 195));
        viewallbutton.setText("View All");
        viewallbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewallbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(viewallbutton);
        viewallbutton.setBounds(50, 250, 100, 30);

        backbutton.setBackground(new java.awt.Color(97, 212, 195));
        backbutton.setText("Back");
        backbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(backbutton);
        backbutton.setBounds(210, 200, 90, 30);

        addregionbutton.setBackground(new java.awt.Color(97, 212, 195));
        addregionbutton.setText("Add Region");
        addregionbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addregionbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(addregionbutton);
        addregionbutton.setBounds(50, 200, 100, 30);
        jPanel1.add(jTfaddregion);
        jTfaddregion.setBounds(160, 150, 140, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter Region:-");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 150, 100, 24);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Region Update");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(110, 80, 132, 41);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MAHADEV FOAM AND FURNISHING");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(75, 11, 410, 50);

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator7);
        jSeparator7.setBounds(40, 130, 270, 2);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 520, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
       new Dealer_Portal().setVisible(true);
        dispose(); 
    }//GEN-LAST:event_backbuttonActionPerformed

    private void addregionbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addregionbuttonActionPerformed
            try
       { 
         Class.forName("java.sql.Driver");
         Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mahadev_foam","root","admin");
         Statement stmt = conn.createStatement();
           // int id=Integer.parseInt(jTfid.getText());
           //int id2=id+1;
            String region=jTfaddregion.getText();
            String sql = "insert into region_list values('"+region+"');";
		      //"insert into list values('region');"

		stmt.executeUpdate(sql);
           //     jTfid.setText(id2+"");
                jTfaddregion.setText(null);
                JOptionPane.showMessageDialog(this,"Region added Sucessfully...");  
                
}
        catch(Exception e)
       {
           JOptionPane.showMessageDialog(this, e.getMessage());
       }
    }//GEN-LAST:event_addregionbuttonActionPerformed

    private void viewallbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewallbuttonActionPerformed
        try{
        DefaultTableModel model=(DefaultTableModel)jregiontable.getModel();
        
        Class.forName("java.sql.Driver");
        Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mahadev_foam","root","admin");
        Statement stmt=conn.createStatement();
    
    String sql="select * from region_List;";
    	
    ResultSet rs=stmt.executeQuery(sql);
    
    int rows=model.getRowCount();
    if(rows>0)
        {
            for (int i=0;i<rows;i++)
            {
                model.removeRow(0);
            }
        }
        while(rs.next())
        {
            model.addRow(new Object[]{rs.getString(1)});
        }
    
    }    
    catch(Exception e)
    {
            JOptionPane.showMessageDialog(this, "Database Connection Error.....!"); 
    }
    }//GEN-LAST:event_viewallbuttonActionPerformed

    private void searchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbuttonActionPerformed
          try {
            DefaultTableModel model=(DefaultTableModel)jregiontable.getModel();
            Class.forName("java.sql.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mahadev_foam","root","admin");
            Statement stmt = conn.createStatement();
            String region = (jTfaddregion.getText());
            String sql = "SELECT * FROM region_list where region like '%"+region+"%';";
                        //select * from region_list where region like '%r%';
            ResultSet rs = stmt.executeQuery(sql);
    
            int rows=model.getRowCount();
        if(rows>=0)
        {
            for (int i=0;i<rows;i++)
            {
                model.removeRow(0);
            }
        
                while(rs.next())
                {
                    model.addRow(new Object[]{rs.getString(1)});
                }
                
        }
          }
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_searchbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_region_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_region_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_region_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_region_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_region_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addregionbutton;
    private javax.swing.JButton backbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField jTfaddregion;
    private javax.swing.JTable jregiontable;
    private javax.swing.JButton searchbutton;
    private javax.swing.JButton viewallbutton;
    // End of variables declaration//GEN-END:variables
}
