/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mahadevfoam_dealers;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Student
 */
public class dealer_details_portal extends javax.swing.JFrame {

    /**
     * Creates new form dealer_details_portal
     */
    public dealer_details_portal() {
        initComponents();
        
        try {
        Class.forName("java.sql.Driver");
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mahadev_foam","root","admin");
        Statement stmt = conn.createStatement();
        String combo_group = "Select DISTINCT delergroup from dealer_group;";
        ResultSet rs = stmt.executeQuery(combo_group);

        
        while(rs.next())
        {
            jComboBoxdealergroup.addItem(rs.getString(1));
        }
        
        String combo_region = "Select DISTINCT region from region_list;";
        rs = stmt.executeQuery(combo_region);
        while(rs.next())
        {
        jComboBoxregion.addItem(rs.getString(1));
        }
        
            } 
        catch (Exception e)
            {
            JOptionPane.showMessageDialog(this, e.getMessage());
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jtingst = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtincst = new javax.swing.JTextField();
        jComboBoxregion = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxdealergroup = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jaddress = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jcontactnumber = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jcontactperson = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jfirmname = new javax.swing.JTextField();
        jid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dealer Modification");
        setPreferredSize(new java.awt.Dimension(540, 540));
        getContentPane().setLayout(null);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("TIN CST:-");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 369, 90, 14);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Firm Name:-");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 55, 150, 24);

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));
        jPanel1.setLayout(null);

        jButton5.setBackground(new java.awt.Color(97, 212, 195));
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(380, 460, 90, 23);

        jButton6.setBackground(new java.awt.Color(97, 212, 195));
        jButton6.setText("Dealer update");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(250, 460, 120, 23);

        jButton1.setBackground(new java.awt.Color(97, 212, 195));
        jButton1.setText("Add Dealer");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(30, 460, 120, 23);

        jButton3.setBackground(new java.awt.Color(97, 212, 195));
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(160, 460, 80, 23);
        jPanel1.add(jtingst);
        jtingst.setBounds(200, 400, 280, 30);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("TIN GST:-");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 410, 90, 14);
        jPanel1.add(jtincst);
        jtincst.setBounds(200, 360, 280, 30);

        jPanel1.add(jComboBoxregion);
        jComboBoxregion.setBounds(200, 320, 280, 30);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Region:-");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 330, 150, 22);

        jPanel1.add(jComboBoxdealergroup);
        jComboBoxdealergroup.setBounds(200, 280, 280, 30);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Dealer Group:-");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 290, 150, 24);

        jaddress.setColumns(20);
        jaddress.setRows(5);
        jScrollPane2.setViewportView(jaddress);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(200, 170, 280, 100);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Address:-");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 210, 150, 23);
        jPanel1.add(jcontactnumber);
        jcontactnumber.setBounds(200, 130, 280, 30);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Contact Number:-");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 130, 150, 22);
        jPanel1.add(jcontactperson);
        jcontactperson.setBounds(200, 90, 280, 30);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contact Person Name:-");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 100, 170, 22);
        jPanel1.add(jfirmname);
        jfirmname.setBounds(200, 50, 280, 30);
        jPanel1.add(jid);
        jid.setBounds(200, 10, 50, 30);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Dealer ID:-");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 20, 150, 24);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 530, 510);
        getContentPane().add(jPanel3);
        jPanel3.setBounds(560, 10, 640, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Class.forName("java.sql.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mahadev_foam","root","admin");
            Statement stmt = conn.createStatement();
            String id=jid.getText();
            String firm_name=jfirmname.getText();
            String contact_person=jcontactperson.getText();
            String contact_number=jcontactnumber.getText();
            String address=jaddress.getText();
            String dealer_group=jComboBoxdealergroup.getSelectedItem().toString();
            String dealer_region=jComboBoxregion.getSelectedItem().toString();
            String tin_cst=jtincst.getText();
            String tin_gst=jtingst.getText();
            
            String sql = "insert into dealer_details values('"+id+"','"+firm_name+"','"+contact_person+"','"+contact_number+"','"+address+"','"+dealer_group+"','"+dealer_region+"','"+tin_cst+"','"+tin_gst+"');";
            stmt.executeUpdate(sql);
            
            
            JOptionPane.showMessageDialog(this,"dealer added Sucessfully...");
            
            } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new Dealer_Portal().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try
        {
            Class.forName("java.sql.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mahadev_foam","root","admin");
            Statement stmt = conn.createStatement();
            String id=jid.getText();
            
            String sqldelete = "delete from dealer_details where dealer_id='"+id+"';";
            stmt.executeUpdate(sqldelete);
            
            JOptionPane.showMessageDialog(this, "dealer deleted..!");
            jid.setText(null);
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
try {
            Class.forName("java.sql.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mahadev_foam","root","admin");
            Statement stmt = conn.createStatement();
            String id=jid.getText();
            String firm_name=jfirmname.getText();
            String contact_person=jcontactperson.getText();
            String contact_number=jcontactnumber.getText();
            String address=jaddress.getText();
            String dealer_group=jComboBoxdealergroup.getSelectedItem().toString();
            String dealer_region=jComboBoxregion.getSelectedItem().toString();
            String tin_cst=jtincst.getText();
            String tin_gst=jtingst.getText();
            
            String sql = "update dealer_details set firm_name='"+firm_name+"',contact_person_name='"+contact_person+"',dealer_contact_number='"+contact_number+"',dealer_address='"+address+"',deal_group='"+dealer_group+"',deal_region='"+dealer_region+"',dealer_tincst='"+tin_cst+"',dealer_tingst='"+tin_gst+"' where dealer_id='"+id+"';";
            stmt.executeUpdate(sql);
            
            
            JOptionPane.showMessageDialog(this,"dealers details updated  Sucessfully...");
            
            } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(this, e.getMessage());  
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dealer_details_portal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dealer_details_portal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dealer_details_portal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dealer_details_portal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dealer_details_portal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBoxdealergroup;
    private javax.swing.JComboBox jComboBoxregion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jaddress;
    private javax.swing.JTextField jcontactnumber;
    private javax.swing.JTextField jcontactperson;
    private javax.swing.JTextField jfirmname;
    private javax.swing.JTextField jid;
    private javax.swing.JTextField jtincst;
    private javax.swing.JTextField jtingst;
    // End of variables declaration//GEN-END:variables
}
