/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mahadevfoam_dealers;

import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.*;


/**
 *
 * @author SAGAR
 */
public class login_page1 extends javax.swing.JFrame {

    /**
     * Creates new form login_page1
     */
    public login_page1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jTfuserid = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jpassfromuser = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jTfnewuserpass = new javax.swing.JPasswordField();
        jTfnewuserid = new javax.swing.JTextField();
        jTfadminid = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jadminpass = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(850, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(97, 212, 195));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 270, 10));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("USERNAME");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jTfuserid.setBackground(new java.awt.Color(97, 212, 195));
        jTfuserid.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTfuserid.setForeground(new java.awt.Color(255, 255, 255));
        jTfuserid.setText("Enter your username");
        jTfuserid.setBorder(null);
        jTfuserid.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jTfuserid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTfuseridMouseClicked(evt);
            }
        });
        jPanel2.add(jTfuserid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 270, -1));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("PASSWORD");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jpassfromuser.setBackground(new java.awt.Color(97, 212, 195));
        jpassfromuser.setForeground(new java.awt.Color(255, 255, 255));
        jpassfromuser.setText("jPasswordField1");
        jpassfromuser.setBorder(null);
        jpassfromuser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jpassfromuserFocusGained(evt);
            }
        });
        jPanel2.add(jpassfromuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 270, 30));

        jButton1.setBackground(new java.awt.Color(36, 47, 65));
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 420, 290));

        jPanel5.setBackground(new java.awt.Color(36, 47, 65));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText(" Sign Up");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("USERNAME");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("PASSWORD");

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));

        jTfnewuserpass.setBackground(new java.awt.Color(36, 47, 65));
        jTfnewuserpass.setForeground(new java.awt.Color(255, 255, 255));
        jTfnewuserpass.setText("jPasswordField1");
        jTfnewuserpass.setBorder(null);
        jTfnewuserpass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTfnewuserpassFocusGained(evt);
            }
        });
        jTfnewuserpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfnewuserpassActionPerformed(evt);
            }
        });

        jTfnewuserid.setBackground(new java.awt.Color(36, 47, 65));
        jTfnewuserid.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTfnewuserid.setForeground(new java.awt.Color(255, 255, 255));
        jTfnewuserid.setText("Enter your username");
        jTfnewuserid.setBorder(null);
        jTfnewuserid.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jTfnewuserid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTfnewuseridMouseClicked(evt);
            }
        });

        jTfadminid.setBackground(new java.awt.Color(36, 47, 65));
        jTfadminid.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTfadminid.setForeground(new java.awt.Color(255, 255, 255));
        jTfadminid.setText("Enter administrator ID");
        jTfadminid.setBorder(null);
        jTfadminid.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jTfadminid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTfadminidFocusGained(evt);
            }
        });
        jTfadminid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfadminidActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("ADMINISTRATOR ID");

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));

        jadminpass.setBackground(new java.awt.Color(36, 47, 65));
        jadminpass.setForeground(new java.awt.Color(255, 255, 255));
        jadminpass.setText("jPasswordField1");
        jadminpass.setBorder(null);
        jadminpass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jadminpassFocusGained(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("ADMINISTRATOR PASSWORD");

        jButton2.setBackground(new java.awt.Color(36, 47, 65));
        jButton2.setText("Sign Up");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 70, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jTfnewuserid, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTfnewuserpass, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jTfadminid, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jadminpass, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 80, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jButton2))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTfnewuserid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTfnewuserpass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTfadminid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jadminpass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 420, 550));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MAHADEV FOAM AND FURNISHING");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 410, 50));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("BUSINESS MANAGEMENT SYSTEM");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 842, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTfadminidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfadminidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfadminidActionPerformed

    private void jTfnewuseridMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTfnewuseridMouseClicked
        // TODO add your handling code here:
        jTfnewuserid.setText("");
    }//GEN-LAST:event_jTfnewuseridMouseClicked

    private void jTfadminidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTfadminidFocusGained
        // TODO add your handling code here:
         jTfadminid.setText("");
    }//GEN-LAST:event_jTfadminidFocusGained
    
    private void jTfnewuserpassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTfnewuserpassFocusGained
        // TODO add your handling code here:
        jTfnewuserpass.setText("");
    }//GEN-LAST:event_jTfnewuserpassFocusGained

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:   
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jadminpassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jadminpassFocusGained
        jadminpass.setText(null);
    }//GEN-LAST:event_jadminpassFocusGained

    private void jTfuseridMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTfuseridMouseClicked
        jTfuserid.setText(null);
    }//GEN-LAST:event_jTfuseridMouseClicked

    private void jpassfromuserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jpassfromuserFocusGained
        jpassfromuser.setText(null);
    }//GEN-LAST:event_jpassfromuserFocusGained

    private void jTfnewuserpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfnewuserpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfnewuserpassActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try
       { 
         Class.forName("java.sql.Driver");
         Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mahadev_foam","root","admin");
         Statement stmt = conn.createStatement();
         String useridfromuser = jTfuserid.getText();
         String passwordfromuser =jpassfromuser.getText();
         String sql = "SELECT * FROM login where userid='"+useridfromuser+"';";
         ResultSet rs = stmt.executeQuery(sql);
         
                 
         //String password=rs.getString("password");
         if(rs.next()) 
         {         
            String password=rs.getString("password");  // password from database
            if(password.equals(passwordfromuser))
            {
              new mahadev_menu_page().setVisible(true);
              dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Check username or password..!");
            }
         }
         
       }
       catch(Exception e)
       {
           JOptionPane.showMessageDialog(this, e.getMessage());
       }  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try
       { 
         Class.forName("java.sql.Driver");
         Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mahadev_foam","root","admin");
         Statement stmt = conn.createStatement();
         String newuser = jTfnewuserid.getText();
         String newpassword =jTfnewuserpass.getText();
         String adminid = jTfadminid.getText();
         String adminpass = jadminpass.getText();
         String sql = "SELECT * FROM login where userid='"+adminid+"';";
         ResultSet rs = stmt.executeQuery(sql);
         
         //String password=rs.getString("password");
         if(rs.next()) 
         {         
            String password=rs.getString("password");
            if(password.equals(adminpass))
            {
                String sqlinsert = "INSERT INTO LOGIN VALUES('"+newuser+"','"+newpassword+"');";
                                  //insert into login values('newuser','newpassword');
                stmt.executeUpdate(sqlinsert);
                JOptionPane.showMessageDialog(this, "New User Created..!");
                jTfadminid.setText(null);
                jTfnewuserid.setText(null);
                jTfnewuserpass.setText(null);
                jadminpass.setText(null);
                new mahadev_menu_page().setVisible(true);
                dispose();
                
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Check admin userid or pass..!");
            }
         }
         
       }
       catch(HeadlessException e)
       {
           JOptionPane.showMessageDialog(this, e.getMessage());
       } catch (ClassNotFoundException e) {
           JOptionPane.showMessageDialog(this, e.getMessage());
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new login_page1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField jTfadminid;
    private javax.swing.JTextField jTfnewuserid;
    private javax.swing.JPasswordField jTfnewuserpass;
    private javax.swing.JTextField jTfuserid;
    private javax.swing.JPasswordField jadminpass;
    private javax.swing.JPasswordField jpassfromuser;
    // End of variables declaration//GEN-END:variables
}
