/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mahadevfoam_dealers;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mahadav
 */
public class payments1 extends javax.swing.JFrame {

    /**
     * Creates new form payments
     */
    public payments1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        update = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        show = new javax.swing.JButton();
        jtfbalance = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfrcv = new javax.swing.JTextField();
        jtfnet = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        categorybox = new javax.swing.JComboBox();
        jtfinvoiceid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Payments");
        setPreferredSize(new java.awt.Dimension(640, 395));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));
        jPanel1.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Invoice no.", "Name", "Amount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(290, 130, 315, 198);

        update.setBackground(new java.awt.Color(97, 212, 195));
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update);
        update.setBounds(40, 320, 116, 23);

        jButton4.setBackground(new java.awt.Color(97, 212, 195));
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(170, 320, 101, 23);

        show.setBackground(new java.awt.Color(97, 212, 195));
        show.setText("Show outstandings");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });
        jPanel1.add(show);
        show.setBounds(40, 290, 230, 23);

        jtfbalance.setEditable(false);
        jPanel1.add(jtfbalance);
        jtfbalance.setBounds(160, 250, 105, 30);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Balance amount:-");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 250, 104, 24);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Received amount:-");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 210, 104, 24);

        jtfrcv.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfrcvFocusLost(evt);
            }
        });
        jPanel1.add(jtfrcv);
        jtfrcv.setBounds(160, 210, 105, 30);
        jPanel1.add(jtfnet);
        jtfnet.setBounds(160, 170, 105, 30);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Net Amount:-");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 170, 104, 24);

        categorybox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Retail", "Wholesale" }));
        jPanel1.add(categorybox);
        categorybox.setBounds(40, 140, 93, 20);

        jtfinvoiceid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfinvoiceidFocusLost(evt);
            }
        });
        jPanel1.add(jtfinvoiceid);
        jtfinvoiceid.setBounds(160, 110, 109, 30);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter Invoice ID:-");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 110, 170, 22);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("MAHADEV FOAM AND FURNISHING");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(120, 10, 410, 50);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Payments");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(260, 50, 100, 41);

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator7);
        jSeparator7.setBounds(20, 90, 590, 2);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 670, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfinvoiceidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfinvoiceidFocusLost
        try 
        {
                Class.forName("java.sql.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mahadev_foam","root","admin");
                 Statement stmt = conn.createStatement();
          
                int index=categorybox.getSelectedIndex();
                if (index==0){
                int invoiceid=Integer.parseInt(jtfinvoiceid.getText());
                String sql="select netamt,recdamt,balanceamt from payments_retail where invoice_id='"+invoiceid+"';";
                ResultSet rs=stmt.executeQuery(sql);
                if(rs.next()){
                jtfnet.setText(rs.getString("netamt"));
                jtfrcv.setText(rs.getString("recdamt"));
                jtfbalance.setText(rs.getString("balanceamt"));
                }
                }
                if(index==1)
                {
                int invoiceid=Integer.parseInt(jtfinvoiceid.getText());
                String sql="select netamt,recdamt,balanceamt from payments_wholesale where invoice_id='"+invoiceid+"';";
                ResultSet rs=stmt.executeQuery(sql);
                if(rs.next()){
                jtfnet.setText(rs.getString("netamt"));
                jtfrcv.setText(rs.getString("recdamt"));
                jtfbalance.setText(rs.getString("balanceamt"));   
                }
                }
                
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }//GEN-LAST:event_jtfinvoiceidFocusLost

    private void jtfrcvFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfrcvFocusLost
                int rcvamt=Integer.parseInt(jtfrcv.getText());
                int netamt=Integer.parseInt(jtfnet.getText());
                int balanceamt=netamt-rcvamt;
                jtfbalance.setText(""+balanceamt);      
    }//GEN-LAST:event_jtfrcvFocusLost

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
                
        try {
                Class.forName("java.sql.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mahadev_foam","root","admin");
                 Statement stmt = conn.createStatement();
                int rcvamt=Integer.parseInt(jtfrcv.getText());
                int balanceamt=Integer.parseInt(jtfbalance.getText());
                
                String invoiceid=jtfinvoiceid.getText();
                int index=categorybox.getSelectedIndex();
                
                if(index==0){
                String sqlupdate="update payments_retail set recdamt='"+rcvamt+"',balanceamt='"+balanceamt+"' where invoice_id='"+invoiceid+"';";
                stmt.executeUpdate(sqlupdate);
                }
                
                if(index==1)
                {
                String sqlupdate="update payments_wholesale set recdamt='"+rcvamt+"',balanceamt='"+balanceamt+"' where invoice_id='"+invoiceid+"';";
                stmt.executeUpdate(sqlupdate);
                }
                
                JOptionPane.showMessageDialog(this, "payment done. ");
                jtfinvoiceid.setText(null);
                jtfbalance.setText(null);
                jtfnet.setText(null);
                jtfrcv.setText(null);
                
                
        }
        catch (Exception e) 
        {
                JOptionPane.showMessageDialog(this, e.getMessage());
        }
               
                
    }//GEN-LAST:event_updateActionPerformed

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
try{
    
    Class.forName("java.sql.Driver");
    Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mahadev_foam","root","admin");
    Statement stmt=conn.createStatement();
    int index=categorybox.getSelectedIndex();
                
   if(index==0)
   {
    String sql="select p.Invoice_id, c.cus_name, p.balanceamt from payments_retail p, customer_details c where c.cus_id=p.Invoice_id and balanceamt>0;";
    ResultSet rs=stmt.executeQuery(sql);
    int rows=model.getRowCount();
    if(rows>0)
    {
        for(int i=0;i<rows;i++)
        {
            model.removeRow(0);
        }          
    }
    while(rs.next())
    {
        model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3)});   
    }
    
    }
    else if(index==1)
    {
    String sql="select w.Invoice_id, d.firm_name, w.balanceamt from payments_wholesale w, dealer_details d where d.dealer_id=w.Invoice_id and balanceamt>0;";
    ResultSet rs=stmt.executeQuery(sql);
       int rows=model.getRowCount();
    if(rows>0)
    {
        for(int i=0;i<rows;i++)
        {
            model.removeRow(0);
        }          
    }
    while(rs.next())
    {
        model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3)});   
    }
    }
}
 catch(Exception e)
 {
        JOptionPane.showMessageDialog(this, "Database Connection Error.....!"); 
}           

    }//GEN-LAST:event_showActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new mahadev_menu_page().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(payments1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(payments1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(payments1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(payments1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new payments1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox categorybox;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jtfbalance;
    private javax.swing.JTextField jtfinvoiceid;
    private javax.swing.JTextField jtfnet;
    private javax.swing.JTextField jtfrcv;
    private javax.swing.JButton show;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
