/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mahadevfoam_dealers;

import com.sun.crypto.provider.RSACipher;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.management.Query;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Student
 */
public class purchase_challan_input extends javax.swing.JFrame {

    /**
     * Creates new form purchase_challan_input
     */
    public purchase_challan_input() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jspinnerdate = new javax.swing.JSpinner();
        Jinvoicenumberpur = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        addtostock = new javax.swing.JButton();
        jvendorname = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jCombogodown = new javax.swing.JComboBox();
        jtfupi = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jtfnetamt = new javax.swing.JTextField();
        jtfquant = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jtfmrp = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtpurchase = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtflength = new javax.swing.JTextField();
        jtfwidth = new javax.swing.JTextField();
        jtfheight = new javax.swing.JTextField();
        jcomboproductselect = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jcombocompanyselect = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfvendor_id = new javax.swing.JTextField();
        jtfnettotal = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jcusphone = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jcusaddress = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jcusnamebill = new javax.swing.JTextField();
        Jinvoicedate = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        Jinvoicenumberbill = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        Jcusidbill = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("New Purchase Invoice");
        setPreferredSize(new java.awt.Dimension(1030, 550));
        getContentPane().setLayout(null);

        jspinnerdate.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1528298640000L), null, new java.util.Date(1528298640000L), java.util.Calendar.DAY_OF_MONTH));
        jspinnerdate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jspinnerdate.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jspinnerdateStateChanged(evt);
            }
        });
        getContentPane().add(jspinnerdate);
        jspinnerdate.setBounds(119, 18, 140, 31);

        Jinvoicenumberpur.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JinvoicenumberpurFocusGained(evt);
            }
        });
        Jinvoicenumberpur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JinvoicenumberpurActionPerformed(evt);
            }
        });
        getContentPane().add(Jinvoicenumberpur);
        Jinvoicenumberpur.setBounds(119, 55, 140, 30);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Invoice Id:-");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 55, 140, 23);

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Invoice Date:-");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 18, 140, 27);

        jButton6.setBackground(new java.awt.Color(97, 212, 195));
        jButton6.setText("Back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(147, 481, 80, 23);

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));
        jPanel1.setLayout(null);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Select Size:-");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 240, 140, 40);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Height in MM");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(290, 230, 100, 14);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Length");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(120, 230, 77, 14);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Width ");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(210, 230, 72, 14);

        jButton1.setBackground(new java.awt.Color(97, 212, 195));
        jButton1.setText("Open Vendor portal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(270, 80, 150, 23);

        addtostock.setBackground(new java.awt.Color(97, 212, 195));
        addtostock.setText("Add To Stock");
        addtostock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtostockActionPerformed(evt);
            }
        });
        jPanel1.add(addtostock);
        addtostock.setBounds(20, 480, 120, 23);

        jvendorname.setEditable(false);
        jvendorname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jvendornameActionPerformed(evt);
            }
        });
        jvendorname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jvendornameFocusGained(evt);
            }
        });
        jPanel1.add(jvendorname);
        jvendorname.setBounds(120, 130, 140, 30);

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Godown:-");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(10, 440, 140, 21);

        jCombogodown.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jCombogodownFocusGained(evt);
            }
        });
        jPanel1.add(jCombogodown);
        jCombogodown.setBounds(120, 440, 140, 20);

        jtfupi.setEditable(false);
        jtfupi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfupiActionPerformed(evt);
            }
        });
        jtfupi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfupiFocusGained(evt);
            }
        });
        jPanel1.add(jtfupi);
        jtfupi.setBounds(120, 410, 140, 25);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("UPI:-");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(10, 410, 140, 27);

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Net Value:-");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(10, 380, 140, 25);

        jtfnetamt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfnetamtFocusGained(evt);
            }
        });
        jPanel1.add(jtfnetamt);
        jtfnetamt.setBounds(120, 380, 76, 25);
        jPanel1.add(jtfquant);
        jtfquant.setBounds(120, 350, 76, 25);

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Quantity:-");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(10, 350, 140, 20);

        jtfmrp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfmrpFocusGained(evt);
            }
        });
        jPanel1.add(jtfmrp);
        jtfmrp.setBounds(120, 320, 76, 27);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("MRP:-");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(10, 320, 140, 25);

        jtpurchase.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtpurchaseFocusGained(evt);
            }
        });
        jtpurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtpurchaseActionPerformed(evt);
            }
        });
        jPanel1.add(jtpurchase);
        jtpurchase.setBounds(120, 290, 76, 27);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Purchase Price:-");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 290, 140, 27);
        jPanel1.add(jtflength);
        jtflength.setBounds(120, 250, 77, 30);
        jPanel1.add(jtfwidth);
        jtfwidth.setBounds(210, 250, 72, 30);
        jPanel1.add(jtfheight);
        jtfheight.setBounds(290, 250, 71, 30);

        jcomboproductselect.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jcomboproductselectFocusGained(evt);
            }
        });
        jPanel1.add(jcomboproductselect);
        jcomboproductselect.setBounds(120, 200, 140, 20);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Select Product:-");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 200, 140, 20);

        jcombocompanyselect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcombocompanyselectActionPerformed(evt);
            }
        });
        jcombocompanyselect.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jcombocompanyselectFocusGained(evt);
            }
        });
        jPanel1.add(jcombocompanyselect);
        jcombocompanyselect.setBounds(120, 170, 140, 20);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Select company:-");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 170, 140, 25);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Vendor Name:-");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 130, 140, 20);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Vendor Id:-");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 90, 140, 27);
        jPanel1.add(jtfvendor_id);
        jtfvendor_id.setBounds(120, 90, 140, 30);
        jPanel1.add(jtfnettotal);
        jtfnettotal.setBounds(540, 460, 88, 30);

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Total");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(420, 460, 82, 23);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Comp.", "Product", "L", "W", "H (mm)", "Purchase", "MRP", "Quant.", "Net", "UPI", "Godown"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(420, 260, 590, 191);

        jcusphone.setEditable(false);
        jcusphone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jcusphoneFocusGained(evt);
            }
        });
        jcusphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcusphoneActionPerformed(evt);
            }
        });
        jPanel1.add(jcusphone);
        jcusphone.setBounds(540, 210, 134, 30);

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("vendor Phone:-");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(420, 220, 150, 14);

        jcusaddress.setEditable(false);
        jcusaddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jcusaddressFocusGained(evt);
            }
        });
        jcusaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcusaddressActionPerformed(evt);
            }
        });
        jPanel1.add(jcusaddress);
        jcusaddress.setBounds(540, 170, 213, 30);

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Vendor Address:-");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(420, 180, 160, 14);

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Vendor Name:-");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(420, 140, 150, 14);

        jcusnamebill.setEditable(false);
        jcusnamebill.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jcusnamebillFocusGained(evt);
            }
        });
        jcusnamebill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcusnamebillActionPerformed(evt);
            }
        });
        jPanel1.add(jcusnamebill);
        jcusnamebill.setBounds(540, 130, 213, 30);

        Jinvoicedate.setEditable(false);
        Jinvoicedate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JinvoicedateFocusGained(evt);
            }
        });
        Jinvoicedate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JinvoicedateActionPerformed(evt);
            }
        });
        jPanel1.add(Jinvoicedate);
        Jinvoicedate.setBounds(540, 90, 87, 30);

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Invoice Date:-");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(420, 90, 150, 23);
        jPanel1.add(Jinvoicenumberbill);
        Jinvoicenumberbill.setBounds(540, 10, 88, 30);

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Invoice Id:-");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(420, 10, 150, 23);

        Jcusidbill.setEditable(false);
        Jcusidbill.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JcusidbillFocusGained(evt);
            }
        });
        Jcusidbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcusidbillActionPerformed(evt);
            }
        });
        jPanel1.add(Jcusidbill);
        Jcusidbill.setBounds(540, 50, 87, 30);

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Vendor Id:-");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(420, 60, 130, 14);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1030, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcomboproductselectFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcomboproductselectFocusGained
        try {
            Class.forName("java.sql.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mahadev_foam","root","admin");
            Statement stmt = conn.createStatement();
            String company=jcombocompanyselect.getSelectedItem().toString();
            String companyid= "select cid from COMPANY_LIST where cname='"+company+"';";
            ResultSet rs=stmt.executeQuery(companyid);
            if(rs.next())
            {
                String c_id=rs.getString("cid");
                String PRODUCTLIST = "Select pname from product where cid='"+c_id+"';";
                ResultSet rs1 = stmt.executeQuery(PRODUCTLIST);
                jcomboproductselect.removeAllItems();
                while(rs1.next())
                {
                    jcomboproductselect.addItem(rs1.getString("Pname"));
                }
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jcomboproductselectFocusGained

    private void jcombocompanyselectFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcombocompanyselectFocusGained
        try {
            Class.forName("java.sql.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mahadev_foam","root","admin");
            Statement stmt = conn.createStatement();
            String combo_group = "Select DISTINCT cname from company_list";
            ResultSet rs = stmt.executeQuery(combo_group);

            jcombocompanyselect.removeAllItems();
            while(rs.next())
            {
                jcombocompanyselect.addItem(rs.getString("cname"));
            }

        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jcombocompanyselectFocusGained

    private void jvendornameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jvendornameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jvendornameActionPerformed

    private void jvendornameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jvendornameFocusGained
        try {
             Class.forName("java.sql.Driver");
                    Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mahadev_foam","root","admin");
                    Statement stmt=conn.createStatement();
                    int id=Integer.parseInt(jtfvendor_id.getText());
                    String sql="select firm_name from vendor_details WHERE vendor_id='"+id+"';";
                    ResultSet rs1=stmt.executeQuery(sql);
                    
                    if(rs1.next())
                    {
                      jvendorname.setText(rs1.getString("firm_name"));
                    }
        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jvendornameFocusGained

    private void jspinnerdateStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jspinnerdateStateChanged
        //Spinner
        //Model property

        //jLabel1.setText(new SimpleDateFormat("yyyy-MM-dd").format(jSpinner1.getValue()));
        String date=(new SimpleDateFormat("yyyy-MM-dd").format(jspinnerdate.getValue()));
        // jcusname.setText(date); the value is stored in variable can be directly into database.
    }//GEN-LAST:event_jspinnerdateStateChanged

    private void JinvoicenumberpurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JinvoicenumberpurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JinvoicenumberpurActionPerformed

    private void JinvoicenumberpurFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JinvoicenumberpurFocusGained
        
    }//GEN-LAST:event_JinvoicenumberpurFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Vendor_details().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtfupiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfupiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfupiActionPerformed

    private void jtpurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtpurchaseActionPerformed
      
    }//GEN-LAST:event_jtpurchaseActionPerformed

    private void jtpurchaseFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtpurchaseFocusGained
        // this section will get the purchase price from the database  
        try 
        {
        Class.forName("java.sql.Driver");
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mahadev_foam","root","admin");
        Statement stmt = conn.createStatement();
        
        int length=Integer.parseInt(jtflength.getText());
        int width=Integer.parseInt(jtfwidth.getText());
        int height=Integer.parseInt(jtfheight.getText());
        long sq_inches_per_mm=length*width*height;
        
        String product=jcomboproductselect.getSelectedItem().toString();
        String price_from_db="select purchase_price_72_36 from product where pname='"+product+"';";
        ResultSet rs=stmt.executeQuery(price_from_db);
        
        if(rs.next())
        {
           int price=rs.getInt("purchase_price_72_36");
           long rate=(sq_inches_per_mm*price)/259200;
           jtpurchase.setText(rate+"");
        }
        } 
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jtpurchaseFocusGained

    private void jtfmrpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfmrpFocusGained
              // this section will get the MRP from the database  
        try 
        {
        Class.forName("java.sql.Driver");
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mahadev_foam","root","admin");
        Statement stmt = conn.createStatement();
        
        int length=Integer.parseInt(jtflength.getText());
        int width=Integer.parseInt(jtfwidth.getText());
        int height=Integer.parseInt(jtfheight.getText());
        long sq_inches_per_mm=length*width*height;
        
        String product=jcomboproductselect.getSelectedItem().toString();
        String price_from_db="select price_72_36 from product where pname='"+product+"';";
        ResultSet rs=stmt.executeQuery(price_from_db);
        
        if(rs.next())
        {
           int price=rs.getInt("price_72_36");
           long rate=(sq_inches_per_mm*price)/259200;
           jtfmrp.setText(rate+"");
        }
        } 
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jtfmrpFocusGained

    private void jCombogodownFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jCombogodownFocusGained
        try 
        {
         Class.forName("java.sql.Driver");
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mahadev_foam","root","admin");
        Statement stmt = conn.createStatement();
        String combo_group = "Select DISTINCT region from godown;";
        ResultSet rs = stmt.executeQuery(combo_group);

        
        while(rs.next())
        {
            jCombogodown.addItem(rs.getString(1));
        }   
        } 
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
                    }
    }//GEN-LAST:event_jCombogodownFocusGained

    private void jtfupiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfupiFocusGained
        try
        {
         Class.forName("java.sql.Driver");
          Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mahadev_foam","root","admin");
          Statement stmt = conn.createStatement();
            
         
         String sqlinvoiceid="select ifnull(max(upi),'0') from stock;";
         ResultSet rs=stmt.executeQuery(sqlinvoiceid);
         if(rs.next()){
         String invoiceid=rs.getString("ifnull(max(upi),'0')");
         int maxinvoiceid=Integer.parseInt(invoiceid);
         int newinvoiceid=maxinvoiceid+1;
         jtfupi.setText(""+newinvoiceid);
         }   
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jtfupiFocusGained

    private void jtfnetamtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfnetamtFocusGained
        int quant=Integer.parseInt(jtfquant.getText());
        int purchase=Integer.parseInt(jtpurchase.getText());
        int netamt=quant*purchase;
        jtfnetamt.setText(netamt+"");
    }//GEN-LAST:event_jtfnetamtFocusGained

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        new mahadev_menu_page().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void addtostockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtostockActionPerformed
        try 
        {
          Class.forName("java.sql.Driver");
          Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mahadev_foam","root","admin");
          Statement stmt = conn.createStatement();
          
          String date=(new SimpleDateFormat("yyyy-MM-dd").format(jspinnerdate.getValue()));
          String invoiceid=Jinvoicenumberpur.getText();
          String vendorid=jtfvendor_id.getText();
          String vendorname=jvendorname.getText();
          String company=jcombocompanyselect.getSelectedItem().toString();
          String product=jcomboproductselect.getSelectedItem().toString();
          String length=jtflength.getText();
          String height=jtfheight.getText();
          String width=jtfwidth.getText();
          String purch_price=jtpurchase.getText();
          String mrp=jtfmrp.getText();
          String quant=jtfquant.getText();
          String netamt=jtfnetamt.getText();
          String upi=jtfupi.getText();
          String godown=jCombogodown.getSelectedItem().toString();
          
          String insert_stock="insert into stock values('"+date+"','"+invoiceid+"',"
          + "'"+vendorid+"','"+vendorname+"','"+company+"','"+product+"','"+length+"','"+width+"','"+height+"','"+purch_price+"',"
          + "'"+mrp+"','"+quant+"','"+netamt+"','"+upi+"','"+godown+"')";
          stmt.executeUpdate(insert_stock);
          JOptionPane.showMessageDialog(this, "Item Added to Stock");

          String sql="SELECT s.vendorid,s.vendorname,vendor_address,vendor_contact_number FROM stock s, vendor_details v WHERE v.vendor_id=s.vendorid && invoiceid='"+invoiceid+"';";
          
          ResultSet rs=stmt.executeQuery(sql);
                if(rs.next()){
                Jcusidbill.setText(rs.getString("vendorid"));    
                jcusnamebill.setText(rs.getString("vendorname"));
                jcusaddress.setText(rs.getString("vendor_address"));
                jcusphone.setText(rs.getString("vendor_contact_number"));
                }
                String date1="SELECT invoice_date FROM stock WHERE invoiceid='"+invoiceid+"';";      
                rs=stmt.executeQuery(date1);
                if(rs.next()){
                Jinvoicedate.setText(rs.getString("invoice_date"));
                }
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        int rows=model.getRowCount();

           String sqld="SELECT company, product_name, length, width, height_MM, purch_price, rate , quant , netamt, UPI, GODOWN FROM stock WHERE invoiceid='"+invoiceid+"';";
           rs = stmt.executeQuery(sqld);
                if(rows>0)
                    {
                        for (int i=0;i<rows;i++)
                        {
                            model.removeRow(0);
                        }
                    }
                    while(rs.next())
                    {
                        model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10),rs.getString(11)});
                    }
              
                    String sum="select sum(netamt) from stock where invoiceid="+invoiceid+";";
                    rs=stmt.executeQuery(sum);
                    if(rs.next())
                    {jtfnettotal.setText(rs.getString("sum(netamt)"));}
                    Jinvoicenumberbill.setText(invoiceid);
          } 
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }        
    }//GEN-LAST:event_addtostockActionPerformed

    private void jcombocompanyselectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcombocompanyselectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcombocompanyselectActionPerformed

    private void JinvoicedateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JinvoicedateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JinvoicedateActionPerformed

    private void JinvoicedateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JinvoicedateFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_JinvoicedateFocusGained

    private void jcusaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcusaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcusaddressActionPerformed

    private void jcusaddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcusaddressFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jcusaddressFocusGained

    private void jcusnamebillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcusnamebillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcusnamebillActionPerformed

    private void jcusnamebillFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcusnamebillFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jcusnamebillFocusGained

    private void jcusphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcusphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcusphoneActionPerformed

    private void jcusphoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcusphoneFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jcusphoneFocusGained

    private void JcusidbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcusidbillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JcusidbillActionPerformed

    private void JcusidbillFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JcusidbillFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_JcusidbillFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(purchase_challan_input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(purchase_challan_input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(purchase_challan_input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(purchase_challan_input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new purchase_challan_input().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Jcusidbill;
    private javax.swing.JTextField Jinvoicedate;
    private javax.swing.JTextField Jinvoicenumberbill;
    private javax.swing.JTextField Jinvoicenumberpur;
    private javax.swing.JButton addtostock;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jCombogodown;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox jcombocompanyselect;
    private javax.swing.JComboBox jcomboproductselect;
    private javax.swing.JTextField jcusaddress;
    private javax.swing.JTextField jcusnamebill;
    private javax.swing.JTextField jcusphone;
    private javax.swing.JSpinner jspinnerdate;
    private javax.swing.JTextField jtfheight;
    private javax.swing.JTextField jtflength;
    private javax.swing.JTextField jtfmrp;
    private javax.swing.JTextField jtfnetamt;
    private javax.swing.JTextField jtfnettotal;
    private javax.swing.JTextField jtfquant;
    private javax.swing.JTextField jtfupi;
    private javax.swing.JTextField jtfvendor_id;
    private javax.swing.JTextField jtfwidth;
    private javax.swing.JTextField jtpurchase;
    private javax.swing.JTextField jvendorname;
    // End of variables declaration//GEN-END:variables
}
