/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mahadevfoam_dealers;

import static com.sun.org.apache.xalan.internal.xsltc.compiler.util.Type.String;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author Mahadav
 */
public class quick_task_update extends javax.swing.JFrame {
    private String taskidsql;

    /**
     * Creates new form quick_task_update
     */
    public quick_task_update() {
        initComponents();
    }
    
    public quick_task_update(int cus_deal_id,int invoice_id,String cus_name,String phone) {
        initComponents();
        
        
        try 
        {
          Class.forName("java.sql.Driver");
          Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mahadev_foam","root","admin");
          Statement stmt = conn.createStatement();
          
          jCheckBox1.setSelected(false);
          
          jtfcusid.setText(cus_deal_id+"");
          jtfinvoiceid.setText(invoice_id+"");
          jtfcusname.setText(cus_name);
          jtfphone.setText(phone);
          
          
         String taskidsql="select ifnull(max(taskid),'0') from tasks;";
         ResultSet rs=stmt.executeQuery(taskidsql);
         if(rs.next()){
         String invoiceid=rs.getString("ifnull(max(taskid),'0')");
         int maxinvoiceid=Integer.parseInt(invoiceid);
         int newinvoiceid=maxinvoiceid+1;
         jtftaskid.setText(""+newinvoiceid);
         }  
        } 
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        add = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jtftaskid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfcusid = new javax.swing.JTextField();
        jtfinvoiceid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfphone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtfcusname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quick Task Update");
        setPreferredSize(new java.awt.Dimension(500, 455));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));
        jPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(97, 212, 195));
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(250, 380, 80, 23);

        add.setBackground(new java.awt.Color(97, 212, 195));
        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add);
        add.setBounds(80, 380, 80, 23);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(10, 330, 470, 29);

        jCheckBox1.setBackground(new java.awt.Color(97, 212, 195));
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Select If Office/admin Task");
        jCheckBox1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox1StateChanged(evt);
            }
        });
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(303, 120, 170, 23);

        jtftaskid.setEditable(false);
        jPanel1.add(jtftaskid);
        jtftaskid.setBounds(110, 110, 172, 30);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Task ID:-");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 120, 150, 20);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Customer ID:-");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 160, 130, 20);

        jtfcusid.setEditable(false);
        jPanel1.add(jtfcusid);
        jtfcusid.setBounds(110, 150, 172, 30);

        jtfinvoiceid.setEditable(false);
        jPanel1.add(jtfinvoiceid);
        jtfinvoiceid.setBounds(110, 190, 172, 30);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Invoice ID:-");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 190, 130, 30);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name:-");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 240, 130, 14);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Phone Number");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 270, 130, 20);

        jtfphone.setEditable(false);
        jPanel1.add(jtfphone);
        jtfphone.setBounds(110, 270, 172, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Task 1");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 300, 480, 30);

        jtfcusname.setEditable(false);
        jPanel1.add(jtfcusname);
        jtfcusname.setBounds(110, 230, 172, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ADD QUICK TASK TO THE PANEL");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(130, 50, 210, 25);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("MAHADEV FOAM AND FURNISHING");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(50, 10, 410, 50);

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator7);
        jSeparator7.setBounds(90, 80, 270, 2);

        jButton3.setBackground(new java.awt.Color(97, 212, 195));
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(170, 380, 55, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 500, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
      
        try
        {
          Class.forName("java.sql.Driver");
          Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mahadev_foam","root","admin");
          Statement stmt = conn.createStatement(); 

          String taskid=jtftaskid.getText();
          String cusid=jtfcusid.getText();
          String invoice_id=jtfinvoiceid.getText();
          String name=jtfcusname.getText();
          String  phone=jtfphone.getText();
          String task=jTextField1.getText();
          
          String task_add="insert into tasks values('"+taskid+"','"+cusid+"','"+invoice_id+"','"+name+"','"+phone+"','"+task+"','N');";
          stmt.executeUpdate(task_add);
          JOptionPane.showMessageDialog(this, "Task Added to the Panel");
          
          int temp_taskid=1;
          jLabel6.setText("Task "+(temp_taskid+1));
          
          int main_taskid=Integer.parseInt(jtftaskid.getText());
          jtftaskid.setText((main_taskid+1)+"");
          
          jTextField1.setText(null);
          
        } 
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
          
    }//GEN-LAST:event_addActionPerformed

    private void jCheckBox1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox1StateChanged
        try 
        {
            Class.forName("java.sql.Driver");
          Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mahadev_foam","root","admin");
          Statement stmt = conn.createStatement();
          
         String taskidsql="select ifnull(max(taskid),'0') from tasks;";
         ResultSet rs=stmt.executeQuery(taskidsql);
         if(rs.next()){
         String invoiceid=rs.getString("ifnull(max(taskid),'0')");
         int maxinvoiceid=Integer.parseInt(invoiceid);
         int newinvoiceid=maxinvoiceid+1;
         jtftaskid.setText(""+newinvoiceid);
         
           if(jCheckBox1.isSelected())
        {
            jtfcusid.setText(0+"");
            jtfinvoiceid.setText(0+"");
            jtfcusname.setText("Mahadev Foam");
            jtfphone.setText("N/A");
        }    
         }    
        } 
        catch (Exception e) 
        {
           JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
      
    }//GEN-LAST:event_jCheckBox1StateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new mahadev_menu_page().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quick_task_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quick_task_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quick_task_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quick_task_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quick_task_update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jtfcusid;
    private javax.swing.JTextField jtfcusname;
    private javax.swing.JTextField jtfinvoiceid;
    private javax.swing.JTextField jtfphone;
    private javax.swing.JTextField jtftaskid;
    // End of variables declaration//GEN-END:variables
}
